//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetBuilder.Core
{
    using System;
    using System.Collections.Generic;
    using NuGetBuilder.Core;
    
    
    public class PackageDefinition
    {
        
        // NuGet package id.
        public string Id { get; set; }
        
        // NuGet package summary (shown in VS packages browser window).
        public string Summary { get; set; }
        
        // NuGet package description.
        public string Description { get; set; }
        
        // An array of package authors.
        public List<string> Authors { get; set; }
        
        // An array of package owners.
        public List<string> Owners { get; set; }
        
        // Package dependencies.
        public List<PackageDependency> Dependencies { get; set; }
        
        // Git repository
        public string GitUrl { get; set; }
        
        // Package sources
        public List<string> Sources { get; set; }
        
        // Package destinations
        public List<string> Destinations { get; set; }
    }
}
