//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetBuilder.Core
{
    using System;
    
    
    public class PackageDependency
    {
        
        public string DepId { get; set; }
        
        public string Version { get; set; }
    }
}
